steps:
- name: 'node:22'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    npm install
    npm run build
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dupay-433708/my-react-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dupay-433708/my-app']
images:
- 'gcr.io/dupay-433708/my-app'
